apiVersion: v1
kind: Pod
metadata:
  name: nnode-affinityx
spec:
  affinity:
    nodeAffinity:
    #hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: " lables like topology.kubernetes.io/zone:"
            operator: In
            values:
            - "lable value like us-east-1b"
          # - key: disktype
          #   operator: In
          #   values:
          #   - ssd
      #soft rule
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop

      - weight: 10
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop


  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent